// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp_pJuKCM1saiJk4bYY1b6Hh0IYFzSyuQ',
    appId: '1:617750098009:web:d527d8de9b4181ad574148',
    messagingSenderId: '617750098009',
    projectId: 'appsaludbd',
    authDomain: 'appsaludbd.firebaseapp.com',
    storageBucket: 'appsaludbd.appspot.com',
    measurementId: 'G-EVJZMKQHE4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpwZFao9nN4NJJz34LMP7pqgjYpmVr44E',
    appId: '1:617750098009:android:6c5b88650eaf59ee574148',
    messagingSenderId: '617750098009',
    projectId: 'appsaludbd',
    storageBucket: 'appsaludbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5ggh1-YYDv_721cBZJCeuDihVQIbvVXs',
    appId: '1:617750098009:ios:7c8b2831af7e2fac574148',
    messagingSenderId: '617750098009',
    projectId: 'appsaludbd',
    storageBucket: 'appsaludbd.appspot.com',
    iosClientId: '617750098009-q9dffbgjug7ccbdtergr9hrbdogfenel.apps.googleusercontent.com',
    iosBundleId: 'com.example.appSalud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5ggh1-YYDv_721cBZJCeuDihVQIbvVXs',
    appId: '1:617750098009:ios:7c8b2831af7e2fac574148',
    messagingSenderId: '617750098009',
    projectId: 'appsaludbd',
    storageBucket: 'appsaludbd.appspot.com',
    iosClientId: '617750098009-q9dffbgjug7ccbdtergr9hrbdogfenel.apps.googleusercontent.com',
    iosBundleId: 'com.example.appSalud',
  );
}
